---
- name: Jinja2 filtering demo 3
  hosts: localhost
  connection: local

  vars:
    ping_value: "{{ lookup('file', '/etc/hosts') }}"

  tasks:
   - debug:
       msg: "ping value is {{ ping_value }}"